# Site settings
author: Derek Neal Stiles
title: Becoming A Data Scientist
header-img: img/home-bg.png
email: derek.neal.stiles@gmail.com
copyright_name: Derek Neal Stiles
description: > # this means to ignore newlines until "baseurl:"
  My Adventure Through Flatiron's Data Science Program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dstiles2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
